"""refactor worker

Revision ID: f83a13b1464a
Revises: 35d4142d3ac7
Create Date: 2026-04-12 16:12:31.477026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f83a13b1464a'
down_revision: Union[str, None] = '35d4142d3ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workers_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_name'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_receiptNumber'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_logs_id'), table_name='order_logs')
    op.drop_table('order_logs')
    op.drop_index(op.f('ix_business_profiles_id'), table_name='business_profiles')
    op.drop_table('business_profiles')
    op.drop_index(op.f('ix_portfolio_items_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('image', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_portfolio_items_id'), 'portfolio_items', ['id'], unique=False)
    op.create_table('business_profiles',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('slogan', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('hours', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('instagram', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_business_profiles_id'), 'business_profiles', ['id'], unique=False)
    op.create_table('order_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('note', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('employeeName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('order_logs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_order_logs_id'), 'order_logs', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('garmentType', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('measurements', mysql.JSON(), nullable=True),
    sa.Column('attributes', mysql.JSON(), nullable=True),
    sa.Column('status', mysql.ENUM('RECEIVED', 'CUTTING', 'SEWING', 'FINISHING', 'DONE'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('order_items_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('receiptNumber', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('customerName', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('customerPhone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('paymentStatus', mysql.ENUM('PAID', 'UNPAID', 'PARTIAL'), nullable=False),
    sa.Column('totalPrice', mysql.FLOAT(), nullable=True),
    sa.Column('paidAmount', mysql.FLOAT(), nullable=True),
    sa.Column('deadline', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('notes', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('createdAt', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updatedAt', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_orders_receiptNumber'), 'orders', ['receiptNumber'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('workers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('role', mysql.ENUM('POTONG', 'JAHIT', 'FINISHING'), nullable=True),
    sa.Column('status', mysql.ENUM('WORKING', 'IDLE'), nullable=True),
    sa.Column('wagePerPiece', mysql.FLOAT(), nullable=True),
    sa.Column('currentTask', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('weeklyCompleted', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_joined', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_workers_name'), 'workers', ['name'], unique=False)
    op.create_index(op.f('ix_workers_id'), 'workers', ['id'], unique=False)
    # ### end Alembic commands ###
