"""empty message

Revision ID: 121659432d41
Revises: 2f42ad7f7a53
Create Date: 2026-05-16 16:36:31.838018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '121659432d41'
down_revision: Union[str, None] = '2f42ad7f7a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_items_ibfk_1'), 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'assigned_worker_id')
    op.drop_column('order_items', 'assigned_worker_name')
    op.add_column('order_logs', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.add_column('order_logs', sa.Column('worker_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'order_logs', 'workers', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_logs_ibfk_2', 'order_logs', type_='foreignkey')
    op.drop_column('order_logs', 'worker_name')
    op.drop_column('order_logs', 'worker_id')
    op.add_column('order_items', sa.Column('assigned_worker_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('order_items', sa.Column('assigned_worker_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('order_items_ibfk_1', 'order_items', 'workers', ['assigned_worker_id'], ['id'])
    # ### end Alembic commands ###
