"""add_sketch_to_order_item

Revision ID: 5aac38218baf
Revises: f83a13b1464a
Create Date: 2026-04-14 16:45:35.338498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aac38218baf'
down_revision: Union[str, None] = 'f83a13b1464a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
