"""add_table_garment_type

Revision ID: 848d4f698e2d
Revises: ec37e9a4f2e0
Create Date: 2026-04-29 20:59:20.267635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '848d4f698e2d'
down_revision: Union[str, None] = 'ec37e9a4f2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garment_types', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('order_items', sa.Column('garmentTypeId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'garment_types', ['garmentTypeId'], ['id'])
    op.drop_column('order_items', 'garmentType')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('garmentType', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'garmentTypeId')
    op.drop_column('garment_types', 'is_deleted')
    # ### end Alembic commands ###
